/*
	This is a first attempt at creating data formats.  We are probably going to need to modify this heavily.
	Created May 18, 2026, by Robert Lemke Oliver.
*/

/*
	For a permutation group G, we want to record:
		1) Malle's a(G) (Integer)
		2) Malle's b(G) (Integer)
		3) Wang's b(G) (Integer)
		4) Whether the group is concentrated (Boolean)
		5) The subgroup generated by the minimal index elements (Permutation group)
		6) Whether the group is semiconcentrated (Boolean)
		7) The sugbroups associated with each conjugacy class of minimal index elements
		8) Loughran--Santens's c(G) (Real)
		9) Generators for the Brauer group (List of central extensions?)
		10) Tame Euler factors (Rational function, or maybe a sequence of such)
		11) Wild Euler factors (Sequence of Rational numbers)
		12) Brauer--Manin obstruction (Bool ean)
		13) Asymptotic known? (Boolean)
		14) Asymptotic expansion? (Probably two lists, one of exponents (with log powers, I guess), one with coefficients)
		15) Best known upper bound for discriminant counting over Q(Real number)
		16) Best known lower bound for discriminant counting over Q (Real number)
		17) Best known upper bounds over a general number field, with discriminant uniformity (Two real numbers)
		
	I'll also set this up to record some extra data in case it's useful.  We'll probably also want to have a good way to link this to the abstract group record.
*/

NFPermGroupRec
	:=recformat< 
	//Basics about the group
		degree:RngIntElt, 
		label:RngIntElt, 
		order:RngIntElt, 
		nilpotent:BoolElt,
		solvable:BoolElt,
		
	//Information for the database
		malle_a:RngIntElt, 
		malle_b:RngIntElt, 
		wang_b:RngIntElt, 
		concentrated:BoolElt,  
		concentrated_subgroup:GrpPerm,
			// ^^ Should probably swap this out for the label or some other way of more efficiently recording it
		semiconcentrated:BoolElt,
		semiconcentrated_subgroups:SeqEnum,
		malle_c:FldReElt,
		brauer_generators:SeqEnum,
		asymptotic_known:BoolElt,
		asymptotic_exponents:SeqEnum,
		asymptotic_coefficients:SeqEnum,
		asymptotic_error:SeqEnum,
		upper_bound,
		lower_bound,
		uniform_upper_bound:SeqEnum
	>;
		
		
		
/*
	For an abstract group G, we want to record:
		1) Region of meromorphicity for the associated multiple Dirichlet series
			Should be given as a sequence of linear forms, with variables indexed by conjugacy classes of cyclic subgroups
		2) Inertial multiplicity bounds
			Should be given as a sequence of linear forms, with variables indexed by conjugacy classes of cyclic subgroups
		3) Galois discriminant information: asymptotic? upper bound? lower bound?
		4) Product of ramified primes information: asymptotic? upper bound? lower bound?
		5) Links to transitive representations: Sequence of pairs (Degree, Id)
	
	We intend to index a lot of this by conjugacy classes of cyclic subgroups.  We'll need to make sure we can consistently label those subgroups for the structures below to work.  
	
	For most of what we're doing, we really only need to keep track of the conjugacy classes of nontrivial cyclic subgroups.
*/

NFAbstractGroupRec
	:=recformat<
	//Basics about the group
		order:RngIntElt,
		label:RngIntElt,
		nilpotent:BoolElt,
		solvable:BoolElt,
		transitive_reps:SeqEnum,
	
	//Information for the database
		meromorphic_mds_forms:SeqEnum,
		inertial_multiplicity_bounds:SeqEnum,
		galois_a:RngIntElt,
		galois_b:RngIntElt,
		galois_asymptotic:BoolElt,
		galois_asymptotic_exponents:SeqEnum,
		galois_asymptotic_coefficients:SeqEnum,
		galois_asymptotic_error:SeqEnum,
		galois_concentrated:BoolElt,
		radical_a:RngIntElt,
		radical_b:RngIntElt,
		radical_asymptotic:BoolElt,
		radical_asymptotic_exponents:SeqEnum,
		radical_asymptotic_coefficients:SeqEnum,
		radical_asymptotic_error:SeqEnum,
		galois_upper_bound,
		radical_upper_bound
	>;
